development:
  adapter: async

test:
  adapter: test

production:
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: shinobi_assist_31491_production
